# Используем официальный образ Node.js версии 22
FROM node:22

# Создаем рабочую директорию в контейнере
WORKDIR /app

# Копируем package.json и package-lock.json (если есть)
COPY package*.json .

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы приложения
COPY . .

# Открываем порт 
EXPOSE 8080

# Команда для запуска приложения 
CMD ["npm", "run", "serve"]